apiVersion: v1
kind: Pod
metadata:
  name: mybot
spec:
  containers:
  - name: mybot
    image: prof222772/mybot:7
    env:
      - name: TOKEN
        valueFrom:
          secretKeyRef:
            name: token
            key: token
